### ISSUE TITLE
tag: Crashed in Twinkle.tag.updateSortOrder

### ISSUE THREAD

**Issue by Xi-Plus** [azatoth/twinkle#1061]
TypeError: Cannot read property 'indexOf' of null
`Twinkle.tag.checkedTags` is null in
https://github.com/azatoth/twinkle/blob/b227cf08231202b5f93621b8b6fd7d2cdf18bf8f/modules/friendlytag.js#L328-L332
Reproduce step: Open Tag panel, then close it, then open it again.

**Comment by Amorymeltzer** [comment]
@Xi-Plus I can't trigger this, is there an example page you can link to?  What browser?

**Comment by Xi-Plus** [comment]
I can reproduce it on any page, including https://en.wikipedia.org/wiki/Wikipedia
On these browsers:
1. Google Chrome 84.0.4147.89 on Windows 10
2. Google Chrome 84.0.4147.89 on Android 9
3. Firefox 78.0.2 on Windows 10
4. Microsoft Edge 44.18362.449.0 on Windows 10

**Comment by Amorymeltzer** [comment]
@Xi-Plus Can you check on enWiki now (maybe clear your cache) and see if it persists?  I reverted the latest slate of changes (except #908).

**Comment by Amorymeltzer** [comment]
Actually, @Xi-Plus, is there a chance this is because you're using your global twinkle?  #908 (specifically, 83c5955) changed `HTMLFormElement.prototype.getChecked` to return `[]` rather than `null`.  That meant `Twinkle.tag.checkedTags = form.getChecked('articleTags') || [];` was just `Twinkle.tag.checkedTags = form.getChecked('articleTags')` but I see that [your global morebits](https://meta.wikimedia.org/wiki/User:Xiplus/Twinkle/morebits.js) doesn't have that change incorporated, so it's still returning `null`.

**Comment by Xi-Plus** [comment]
> is there a chance this is because you're using your global twinkle?

Wow! You're right! I have fixed my global twinkle.
