### ISSUE TITLE
Treat redirects with RfD template as redirects

### ISSUE THREAD

**Issue by Xi-Plus** [azatoth/twinkle#1065]
If there is RfD template on redirects, Twinkle treats it as article (Identified by `mw.config.get('wgIsRedirect')`).
It is recommended to also check RfD template or "Category:Redirects for discussion from XXX" category to identify redirects.
Sample page: https://en.wikipedia.org/w/index.php?title=Death_of_Amir_Tehkal&oldid=969331860

**Comment by Amorymeltzer** [comment]
This is indeed a major complaint of the speedy module, but I'm not entirely sure what the best bet is.  The RfD nomination doesn't have any convenient classes or ids; `twinkleprod` checks the tex for `#invoke:RfD`, which is not ideal here.  Maybe we could modify the module itself?

**Comment by Amorymeltzer** [comment]
Hmm, for items that have an rcat we can check for `.rcat`, so we could use that in an imperfect world.

@siddharthvp You like adding classes to templates/modules, what do you think about adding one to [[Module:RfD]] and/or {{Rcat shell}}?  I can't imagine folks would complain about an `|id` in the latter, although I think Module:RfD would be sufficient?

**Comment by siddharthvp** [comment]
@Amorymeltzer {{Rcat shell}} already had `.box-Redirect_category_shell`. For Module:RfD, I just [added](https://en.wikipedia.org/w/index.php?title=Module:RfD&diff=986499456&oldid=954817046) it (`.box-RfD`)

I was initially thinking we could just use `wgCategories` as Xi-Plus implied, but I'm surprised to see that wgCategories doesn't work while editing or viewing history (why does wgCategories exist at all then? Because while viewing the page we could just scrape #catlinks in the DOM!). So, at the end of the day, detecting neither the template nor category works in edit/history mode.

**Comment by Amorymeltzer** [comment]
Mmm, yes indeed.  And thanks.  And I have no earthly idea why `wgCategories` doesn't.  History is the one I was concerned about, that came up with XfD in #863 (mainly around soft redirects); not sure there's a way back from that.

**Comment by Amorymeltzer** [comment]
Opened #1182; not sure that I think `.rcat` is necessary, nor parsing `#wpTextbox1`, but open to discussion.  As noted there, XfD is left behind 😢
