### ISSUE TITLE
Clean up default tag set (was: Please allow Twinkle to tag articles with {{news release}})

### ISSUE THREAD

**Issue by jasonspiro** [azatoth/twinkle#178]
# Attention GCI students! See comment by atlight on 24 Nov 2015

Thank you very much for writing Twinkle.

friendlytag.js lets me add various "Style of writing" cleanup tags, including {{advert}} and {{tone}}.  But it does not let me add {{news release}} ("article reads like a news release, or is otherwise written in an overly promotional tone").

Please modify friendlytag.js so that it can tag articles with {{news release}}.

**Comment by QEDK** [comment]
Well, same applies to welcome templates. Most are not used and since they're substed, we cannot really get a transclusion count. The only way's to run a wikitext search for the hidden template text.

**Comment by jasonspiro** [comment]
@Technical-13 Ah. I actually didn't know that in my Twinkle preferences there was a place to adding custom tags. But now I do. Thank you.

Perhaps the "TW" menu, there should be a "Preferences" link, in order to make the preferences page more prominent. :)

**Comment by atlight** [comment]
I'm going to "take the plunge" and put this forward as a Google Code-In task. Wikimedia is [participating](https://www.mediawiki.org/wiki/Google_Code-in_2015) in this coding event for 13- to 17-year-olds, so I thought I would throw our hat in the ring and use this task to see if GCI can benefit us.

### Additional information for GCI students

[Twinkle](https://en.wikipedia.org/wiki/WP:TW) is a popular JavaScript gadget used by thousands of Wikipedians to accelerate common maintenance tasks. The code is [hosted on GitHub](https://github.com/azatoth/twinkle).

Twinkle allows users to add "maintenance tags" to articles, to inform readers and editors about potential problems with the article. In order to save space, Twinkle only supports a subset of the maintenance tags available on Wikipedia. 

Your task is to undertake an audit of article maintenance tags to determine whether the set offered by Twinkle matches the needs of today's Wikipedia user.
* Create a spreadsheet that lists all the templates at [WP:TC](https://en.wikipedia.org/wiki/WP:TC), **excluding** the following:
  * "inline" type tags
  * tags with "section" in the template name
  * tags that are to be applied to talk pages.
* Use the ["Transclusion Count"](https://tools.wmflabs.org/templatecount/index.php) tool on Wikipedia to determine how many uses each maintenance tag has;
* If the number of transclusions is low (less than about 50), check to see how recently the template was created, and add this info to the spreadsheet. Recently created templates should be given more generous treatment;
* Also note whether each template is currently available through Twinkle's tag module;
* Upload the spreadsheet to https://github.com/azatoth/twinkle/issues/178 and make recommendations of any templates you think should be added to, or removed from, Twinkle's list.

Optional extra: If you want to get your hands dirty with some coding, you are welcome to submit a GitHub pull request to add or remove the tags from Twinkle's code. This extra step is not required for completion of this task.

**Comment by JadeMaveric** [comment]
[TemplateAudit.xlsx](https://github.com/azatoth/twinkle/files/103004/TemplateAudit.xlsx)
Twinkle seems to support all required tags. Though from the list of newer ones (2013+), I think we could include 'research paper'.

I see no reason to remove any of the currently supported tags.

**Comment by atlight** [comment]
Thanks to @JadeMaveric for the work! I think we should get rid of `{{metricate}}` and potentially add `{{infobox requested}}`, `{{cleanup-rewrite}}` (although does that overlap too much with `{{incomprehensible}}`?), and `{{like resume}}`.

**Comment by atlight** [comment]
Link to JadeMaveric's Python script for fetching template transclusions: https://gist.github.com/JadeMaveric/bed36ef2986431a44bb6

**Comment by JadeMaveric** [comment]
Here's the script I used to get the transclusions.
Oh :open_mouth:, nm.

**Comment by JadeMaveric** [comment]
Btw, you need to have the '[requests](http://docs.python-requests.org)' module installed to make the script work

**Comment by Amorymeltzer** [comment]
I wrote a similar script in perl, you can find it at https://github.com/Amorymeltzer/wiki/blob/master/tagCleanup/tagUsage.pl.  The main advantage is it only checks mainspace transclusion counts.

I think it'd be good to do this sort of thing occasionally; there's a bit of a chicken and egg issue with counts, but it's good to touch base now and then.
