### ISSUE TITLE
The option to add an edit summary when rolling back edits does not appear in Internet Explorer Modern

### ISSUE THREAD

**Issue by gparyani** [azatoth/twinkle#243]
Title explains it all. When rolling back one or more edits as AGF or regular, it just goes ahead and performs the revert without prompting for an edit summary at all. It just acts as though I didn't type anything into the box.

By the way, this only happens in the _Modern_ app version of IE; using the desktop version works around this bug and causes the prompt for the edit summary to be displayed as normal. I've reproduced this issue on IE11 on Windows 8.1, but I think it also happens on IE10 on Windows 8 (not 8.1).

**Comment by atlight** [comment]
This issue only affects Windows 8 and 8.1. It does not appear to affect Windows 10, as the immersive version of Internet Explorer is not included in that OS (as far as I can tell).

I'm going to decline the resolution of this issue, because it affects only a small number of people, and because it is impossible to detect immersive IE on Windows 8.x. It may end up being resolved when #274 is addressed.
