### ISSUE TITLE
Add uw-plotsum1 and uw-plotsum2

### ISSUE THREAD

**Issue by siphedious** [azatoth/twinkle#278]
Could the above templates be added to the User Warnings/Behavior in articles dropdown? I've just added them to https://en.wikipedia.org/wiki/Wikipedia:Template_messages/User_talk_namespace after support at WT:FILM. I initiated a discussion at Wikipedia talk:Template messages/User talk namespace where nobody objected to the templates after 5 days.

Thanks!

**Comment by atlight** [comment]
In order to avoid a excessively long list of templates in the warn dialog box, we only include a selection of the most common user warning template series. Little-used template series, such as uw-icsX, are omitted from Twinkle. (We never got around to pruning the single-issue lists, so they are as long as ever...)

As such I am a little hesitant to add these. However, I am also wondering whether we need to rethink our warning list - whether we should include more template series in the list...

**Comment by siphedious** [comment]
Thanks for your response! I know at WT:FILM there's a fair amount of interest in these, and they would presumably be of interest to other projects as well, but I admittedly can't speak to the overarching amount of interest. I use them quite a bit myself.

Thanks for your consideration, either way!

**Comment by Amorymeltzer** [comment]
Agree with the above, and better discussed in #412
