### ISSUE TITLE
Feature Request: Add a XFD log like one already exists for PROD and CSD

### ISSUE THREAD

**Issue by Jab843** [azatoth/twinkle#303]
It would make it much easier to track the articles submitted for XFD and shouldn't take up too much new coding as it already exists.

**Comment by atlight** [comment]
The reason why the CSD and PROD logs exist is that it is impossible for non-admins to keep track of successful CSD and PROD nominations for which the page creator was not notified, because they leave no trace in a user's contributions. On the contrary, XFDs remain perpetually visible in contributions.

I would really prefer to see such a tool implemented on Tool Labs. This would have benefits to users and non-users of Twinkle alike. Such a tool could also include information, such as the outcome of the deletion discussion, which is not possible to include in a log entry at the time of nomination. This last point is a big reason why I don't think adding an XFD log to Twinkle would be very popular or useful to the majority of people.

I'm very much inclined to close this issue; I'll wait to see if anyone else wants to comment.

**Comment by MusikAnimal** [comment]
To be fair it seems we've had this request made multiple times, but I'm ok with not doing it for the reasons outlined above. There's the [AfD stats tool](http://tools.wmflabs.org/afdstats/) but it obviously only covers AfD. Maybe once I get bored with bot work and have cleared out my Twinkle to-dos I can make an attempt at such a tool.

**Comment by MusikAnimal** [comment]
Also I will note that while the CSD/PROD tagging of a page is lost once deleted, you could still do an [edit summary search](https://tools.wmflabs.org/sigma/summary.py) for the notification sent to the page creator, if they've opted to do that. That's how we identify page curation edits at RfA or when they have been using Twinkle without logging. The same is true for XfDs, you can search edit summaries for those just as easily.
