### ISSUE TITLE
Fail to load

### ISSUE THREAD

**Issue by RileyHuntley** [azatoth/twinkle#315]
TW is turned on in Gadgets for me, but WP:TW/P says I must have it installed and TW in generalfails to load.

**Comment by gparyani** [comment]
To help us see if your issue is not occurring due to your Web browser, please post your browser, browser version, and operating system version here. If you don't know how to identify those, please go to http://useragentstring.com/ in the same Web browser that gives you the problem and paste the contents of the big box there.

**Comment by RileyHuntley** [comment]
Now functioning
