### ISSUE TITLE
Create discussion before tagging page

### ISSUE THREAD

**Issue by OdMishehu** [azatoth/twinkle#317]
I think that the discussion should be created before, not after, the page gets tagged. This makes a big difference in AfD and MfD, where a new page is created for the discussion - and where, possibly for the entire time the discussion is open, the link to the discussion remains red. See https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(technical)#How_long_does_it_take_for_a_page_to_update.3F for a place where this came up.

**Comment by gparyani** [comment]
Or, why don't you just purge the pages after they are tagged, to make the link blue again? Whenever I come across such a blue link that has been cached as red (very, very often), I always purge it to make it blue.

But yes, changing the order will prevent the link from being cached as red as it would have ben blue before the link is even added.

**Comment by Amorymeltzer** [comment]
Is this still an issue?  I've not seen it.  As noted in #379, this might complicate a (future) notification if the page has been moved/redirected.  More importantly, the page tag needs to be first so that we can check to see if there are other AfD or CSD tags the user wants to preempt.

Other options like #364 are probably the way to go, so closing this in favor of that (if it's still an issue).
