### ISSUE TITLE
F8 "on Commons" halting error

### ISSUE THREAD

**Issue by owcz** [azatoth/twinkle#340]
I've been getting this error on F8s I believe for a while. I'll enter a file name of the equivalent upload on Commons and get this error when I click to go ahead:
```
Building deletion summary: Unable to generate summary from deletion template
Asking for reason: you didn't give one. I don't know... what with admins and their apathetic antics... I give up...
```

(Can probably remove the snarky message too, especially when the admin's not being apathetic.)

Appreciate your help. It's hard to imagine life without Twinkle.

**Comment by atlight** [comment]
@MusikAnimal, one for you, I think. A couple of points from this: the message is not "snarky", it's supposed to be humorous. But in this case it's not the admin's fault that they are seeing the message, so it shouldn't be shown. And perhaps the deletion summary fetching code needs to be more resilient.

**Comment by MusikAnimal** [comment]
Fixed with https://en.wikipedia.org/w/index.php?title=Template:Now_Commons&diff=739520631&oldid=735707172

It's true the deletion reasons fail if someone broke the template (or didn't include `#delete-reason` in the markup). This isn't a problem for the speedy templates because {{db-meta}} takes care of that, and less likely to be mucked with. The others we'll have to handle one by one I suppose... the advantage here again is that anyone can change the deletion summary without having to go through a Twinkle developer. If you use the native interface to delete a page, it will also populate whatever `#deletion-reason` is into the deletion summary, so it made sense to me for Twinkle to behave in the same way, and keep our summaries centralized and on-wiki.

**Comment by MusikAnimal** [comment]
Also @owcz sorry for taking so long to get to this :/
