### ISSUE TITLE
Twinkle JS does not reload after RevisionSlider is used to switch diffs

### ISSUE THREAD

**Issue by addshore** [azatoth/twinkle#360]
Twinkle should listen to the JS hooks in core and reinit itself.

https://www.mediawiki.org/wiki/Extension:RevisionSlider#JavaScript_Hooks

**Comment by terrorist96** [comment]
Sadly I'll have to disable RevisionSlider due to this issue. I'd love to be able to use RS and TW together. No news on this being fixed?

**Comment by atlight** [comment]
Twinkle was written well before JS hooks existed in MediaWiki, so that's our excuse. To make matters worse there seems to be no documentation about JS hooks on mediawiki.org, apart from a tiny mention at https://www.mediawiki.org/wiki/ResourceLoader/Core_modules#mediaWiki.hook, so I don't know how we were meant to know that we were able to take advantage of this feature.

Whingeing aside, it doesn't look like that ought to be too troublesome to implement.

**Comment by hartman** [comment]
@atlight 

hooks are 'dom events' to which you can add handlers. These handlers are then guaranteed to run whenever the event is triggered. It functions a bit like document.ready, but also works for JS loaded blobs and are in wide use by wikEd, VE, live preview, ajax preview etc. 

wikipage.content is triggered whenever content is added to the page (either initially for page views, on page preview, or on JS live preview). similarly wikipage.diff is triggered when a 'diff' is inserted in a page. [There are also hooks](https://doc.wikimedia.org/mediawiki-core/master/js/#!/api/mw.hook) for categories, collapsible content, the editform, postedit and a few more.

The contents being added to the page, are passed as a parameter (so you don't query the document, but the blob).

Twinkle can attach to these and reinitialise it's UI.

**Comment by atlight** [comment]
Looks like RevisionSlider is about to be enabled by default: https://lists.wikimedia.org/pipermail/wikitech-l/2017-May/088199.html

So we ought to fix this. I don't have time right now unfortunately.
