### ISSUE TITLE
Do not file SPI cases with no sockpuppets listed

### ISSUE THREAD

**Issue by QEDK** [azatoth/twinkle#372]
Make sure that a sockmaster and atleast one sockpuppet is listed when filing SPI cases.

Faced a problem here: https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/Ascar123

**Comment by QEDK** [comment]
I think this should be easy to fix? @atlight @MusikAnimal

**Comment by Amorymeltzer** [comment]
Was looking at this today* and the issue is really at [twinklearv.js#L653-L658](https://github.com/azatoth/twinkle/blob/master/modules/twinklearv.js#L653-L658) whereby an empty sockpuppet report will lead to a tempting dialog to report a sockmaster with no socks.  This is not ideal, as we don't really want reports without a master or puppets; @MusikAnimal, as a CU, your thoughts?  I can submit a simple PR to just alert if the respective fields are empty and to stop trying to be fancy and helpful by changing `puppetReport`.

*Man I do not enjoy twinklearv
