### ISSUE TITLE
DI tab on history page

### ISSUE THREAD

**Issue by szheng95** [azatoth/twinkle#378]
Sometimes, I find myself tagging a very old file for deletion - often in these cases, it is prudent to check the history before doing anything. But the "DI" tag doesn't come up when I view the history of a file page, I have to go back to the file page itself in order to get the tab and tag the file.

Thanks,
User:Train2104 @ enwiki

**Comment by Amorymeltzer** [comment]
The ability to load on the history page was removed in 8b65bb1b93cf30f15d18c4f0995ae3660f715e0f by adding `document.getElementById("mw-imagepage-section-filehistory"` due to concerns around page loading.  Some real quick testing suggests this isn't an issue?  A lot has changed since then, in particular how twinkle modules are loaded.  Maybe this would work?

**Comment by siddharthvp** [comment]
`document.getElementById("mw-imagepage-section-filehistory")` was added to prevent the module from loading on file pages with no associated file. I would assume that on enwiki such pages would be very rare (as they are eligible for G8 speedy). So, the fix would be to just remove this check, to allow for the better usability of the tool, as szheng95 says.

**Comment by Amorymeltzer** [comment]
Indeed — I ran a query to check out how often these seem to happen — using the canned response from db-imagepage suggests the last 100 of these goes back to mid-2015 and the last 200 go back to November 2013.  Not ideal, perhaps, but certainly low impact!

I'll test 'em out a bit, but I think we can do away with these checks.
