### ISSUE TITLE
Protection template tagging breaks redirects

### ISSUE THREAD

**Issue by bardiharborow** [azatoth/twinkle#408]
This has been happening for ages, e.g. https://en.wikipedia.org/wiki/Special:Diff/825759276

**Comment by Amorymeltzer** [comment]
Issue is with [twinkleprotect.js#L1384-L1387](https://github.com/azatoth/twinkle/blob/master/modules/twinkleprotect.js#L1384-L1387).  Basically, the logic currently can't differentiate between a redirect and something with `noinclude`.  The quick fix would be to rework the logic in that section so that the addition of {{ and }} to `tag` took place ahead of time, then turn the `else if` on L1387 to `if`.

That being said, the fancier way would be to do the above and, once we've determined the page is a redirect, ask if the page has `{{Rcat shell` on it.  If so, do nothing, since that takes care of tags automatically.  I suppose `text.match(/{{Rcat/i)` would do it, but there are a lot of possible [redirects](https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Template:Redirect_category_shell&hidelinks=1&hidetrans=1) for that template.

**Comment by Amorymeltzer** [comment]
`{{(?:redr|this is a redirect|r(?:edirect)?(.?cat.*)?[ _]?sh)` should take care of them all? 
 https://regexr.com/3to54

**Comment by MusikAnimal** [comment]
What if we check for the redirect first, and if present put the <noinclude> after the link? Something like `/#REDIRECT \[\[.*?\]\](.*)/i` then put the <include> code at the beginning of the match (which might be empty). Or we could just put it at then end of the page entirely, but it'd be nicer to have it towards the top, in the event there is other content.

I am quite fond of checking for {{Rcat shell}}, too. We've received many a compliant about the redundant protection templates.

**Comment by Amorymeltzer** [comment]
Sorry, I think you missed a word between "put the" and "after the link?"  I think you mean the tag, and after the `#REDIRECT` link itself?  I was envisioning something like:
````javascript
//untested
} else {
	tag = "{{" + tag + "}}"; //Take care of parens here
	if( params.noinclude ) { //Always check so Template-space redirects don't transclude
		text = "<noinclude>" + tag + "</noinclude>" + text;
	if( Morebits.wiki.isPageRedirect() ) {
		//No {{rcat shell}} found
		if (!txt.value.match(/{{(?:redr|this is a redirect|r(?:edirect)?(?:.?cat.*)?[ _]?sh)/i)) {
			text = text.replace(/#REDIRECT ?(\[\[.*?\]\])(.*)/i, "#REDIRECT $1$2\n\n" + tag) //Is this what you meant?
		}
	} else {
		text = tag + "\n" + text;
	}
	summary = "Adding " + params.tag + Twinkle.getPref('summaryAd');
}
````
FYI I threw a `?` after the space before the brackets, sometimes folks don't include that.

**Comment by Amorymeltzer** [comment]
Just getting back to this — babies gonna baby — but nevermind.  If we always put the tag below the `#REDIRECT` I don't think we ever need the `noinclude`s?  So instead, this should work:
````javascript
} else {
	if( Morebits.wiki.isPageRedirect() ) {
		//Only tag if no {{rcat shell}} is found
		if (!text.match(/{{(?:redr|this is a redirect|r(?:edirect)?(?:.?cat.*)?[ _]?sh)/i)) {
			text = text.replace(/#REDIRECT ?(\[\[.*?\]\])(.*)/i, "#REDIRECT $1$2\n\n{{" + tag + "}}");
		} else {
			Morebits.status.info("Redirect category shell present", "nothing to do");
			return;
		}
	} else if( params.noinclude ) {
		text = "<noinclude>{{" + tag + "}}</noinclude>" + text;
	} else {
		text = "{{" + tag + "}}\n" + text;
	}
	summary = "Adding {{" + params.tag + "}}" + Twinkle.getPref('summaryAd');
}
````

Testing it in userspace seems to work as expected/desired.

**Comment by MusikAnimal** [comment]
Ah, thanks. GitHub tried to render `<noinclude>` which is why it said "put the after the link". I just added the backticks now my message is legible. You are correct that noinclude isn't even needed, so disregard!

What you have at https://github.com/azatoth/twinkle/issues/408#issuecomment-412148109 is basically what I was proposing. Feel free to make a PR and I will help test it! :)
