### ISSUE TITLE
Add uw-blank1, uw-blank2

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#424]
Tracking issue for a problem that is going to be fixed by #412

**Comment by DannyS712** [comment]
@ToBeFree is this issue still needed?

**Comment by ToBeFree** [comment]
Thanks for asking; that depends on what happens to #412. It seems to have been abandoned? If so, #424 should become a normal feature request with its current title.

**Comment by Amorymeltzer** [comment]
Good point on #412.  I've gone and opened #533 to centralize and reboot discussion around criteria for inclusion in the menu.

That being said, I'm not wild about including an incomplete template series — wouldn't that be more likely to confuse people who get to level 3 and... nothing?  The existence of these two was really just because of [one editor](https://en.wikipedia.org/wiki/Wikipedia_talk:Template_messages/User_talk_namespace/Archive_15#Page_blanking_messages) without [much consensus](https://en.wikipedia.org/wiki/Wikipedia:Deletion_review/Log/2017_June_8).  The message in the `uw-delete` series seems fine enough.
