### ISSUE TITLE
morebits textarea controls broken?

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#464]
In Morebits quickform's textarea input, attributes `rows ` and `cols `don't seem to be working. The size of the textarea remains the default despite these attributes being provided.

**Comment by Amorymeltzer** [comment]
Fairly certain this is because it's hardcoded in https://github.com/azatoth/twinkle/blob/master/morebits.css#L94-L99.  `width: 100%` is also apparently part of the skin (at least vector and modern).  I guess the idea was that the function might be useful in the abstract?  At any rate, if you turn all that off it works fine! 😆
