### ISSUE TITLE
Twinkleoptions.js not parsing iusc

### ISSUE THREAD

**Issue by RhinosF1** [azatoth/twinkle#522]
The error 'twinkleoptions.js can not be parsed' is experienced when importing options from another users options file.

See: https://en.wikipedia.org/wiki/User:RhinosF1_(Public)/twinkleoptions.js

**Comment by Amorymeltzer** [comment]
I've mulled this over for a bit, but I don't think it's worth doing.  This isn't commonly done AFAICT, and besides, most alternate accounts have different usecases (different perms, for example) or purposes.  I just don't think it's worth the effort to fallback to parsing the text of that page to see if there's an imported script, especially since doing so could theoretically be a security hole.

**Comment by RhinosF1** [comment]
Understood, Thanks for your response anyway.
