### ISSUE TITLE
The TW Tab name does not show up; an empty space appears at its place. 

### ISSUE THREAD

**Issue by sirshtummala** [azatoth/twinkle#532]
Problem: The TW Tab name does not show up; an empty space appears at its place. 

Site: te.wikipedia.org
Using "Vector" skin.

It doesn't work in both Chrome 72.0.3626.119 (Official Build) (64-bit) and Firefox 65.0.2 (64-bit)

Other Observations: 
1. The TW did work well until recently.
2. In My enwiki account, the tab appears normally.

**Comment by Amorymeltzer** [comment]
From what I can make out, your [Twinkle installation](https://te.wikipedia.org/wiki/%E0%B0%AE%E0%B1%80%E0%B0%A1%E0%B0%BF%E0%B0%AF%E0%B0%BE%E0%B0%B5%E0%B0%BF%E0%B0%95%E0%B1%80:Gadget-Twinkle.js) is old.  I think this particular problem is likely because [mediawiki 1.29 removed](https://www.mediawiki.org/wiki/ResourceLoader/Migration_guide_(users)#mw.util.jsMessage) `mw.util.jsMessage`, which had been deprecated since 1.17.  You should update your Twinkle modules, in particular [this change](https://github.com/azatoth/twinkle/commit/700e337d2bbdcf5a0e942ce2ea6d280ff5f99d57) of `mw.util.jsMessage` to `mw.notify` and the [accompanying change](https://en.wikipedia.org/w/index.php?title=MediaWiki:Gadgets-definition&diff=prev&oldid=870840217) to your [gadget definitions](https://te.wikipedia.org/wiki/%E0%B0%AE%E0%B1%80%E0%B0%A1%E0%B0%BF%E0%B0%AF%E0%B0%BE%E0%B0%B5%E0%B0%BF%E0%B0%95%E0%B1%80:Gadgets-definition).

**Comment by sirshtummala** [comment]
Great! It is working now. Thanks for the quick help.
