### ISSUE TITLE
Move Requests

### ISSUE THREAD

**Issue by MattLongCT** [azatoth/twinkle#644]
Support for Wikipedia:Requested moves & WP:RM/TR

It really shouldn't be that much coding. All it would be is a new module that applies to non-category, non-special pages that opens up a new section of the talk page based off the input from the user. It's basically supported right now under Tags (just not consistently nor for technical requests).

**Comment by siddharthvp** [comment]
Also previously requested at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_40#Add_move_requests

**Comment by Amorymeltzer** [comment]
Seems like this would be something for #488

**Comment by siddharthvp** [comment]
> Seems like this would be something for #488

RM is adding a section to talk page and RM/TR is adding an entry at WP:RMT. Well outside the scope of Tag module, I think. 

@MattLongCT This doesn't require much of coding but the tricky part is deciding _where_ do we provide this option. 

I may be alone here but I think this could go to the XFD module, as that already deals with renaming/merging/what not for categories/files/templates etc.

**Comment by Amorymeltzer** [comment]
>Well outside the scope of Tag module, I think.

I guess I was thinking in terms of functionality, but yeah, that's definitely right.  

>the tricky part is deciding *where* do we provide this option

I imagine this is one reason it hasn't gone anywhere — it doesn't fit well into anything existing and is too small/niche for a one-off.

>this could go to the XFD module

It seems pretty far out from XfD to me.  It's an entirely different venue with an entirely different process for page manipulation.

**Comment by MattLongCT** [comment]
Why not just make a new module that operates like XFD? ¯\_(ツ)_/¯
It could be opt-in if there is significant push-back.

**Comment by siddharthvp** [comment]
> It seems pretty far out from XfD to me. It's an entirely different venue with an entirely different process for page manipulation.

We have completely separate codes for dealing with each of the 6 xfd venues, whether it's for the creation of the dialog or the callbacks. It would be easy to just add RM too along with them, with its separate function for page manipulation. The dialog would look almost exactly same as of CfD/S. Notify checkbox disabled, text field for new name, a checkbox for technical request or not, and a reason textarea.  That's why I felt RM belongs here.

> Why not just make a new module

I guess that too sounds not bad. On articles we currently have only 6 options - CSD, PROD, XFD, Tag, Unlink and Last in the dropdown. So I think it won't be much of additional clutter? It would be more used than Unlink any day. (Unrelated but I think Unlink should only be shown on deleted pages, why would anyone want to unlink an existing page?)

**Comment by Amorymeltzer** [comment]
>We have completely separate codes for dealing with each of the 6 xfd venues

I was actually hoping to deal with some of that in the future.  That being said, with TfD (supposedly) moving to a clearinghouse/RM (as-yet-undetermined) system (at some undetermined point) in the future, it's possible RMs would indeed fit in better.  Hadn't thought of CfD/S, that's a good point.

**Comment by siddharthvp** [comment]
> I was actually hoping to deal with some of that in the future. 

Haven't really looked into it, but that doesn't sound like a good idea. The only places where the codes aren't separate are `getDiscussionWikitext` and `preview`, and both are a mess with a hopeless amount of conditionals.
