### ISSUE TITLE
Warning module: warning information frame doesn't resize with window lower edge

### ISSUE THREAD

**Issue by creffett** [azatoth/twinkle#665]
The lower edge of the "warning information" frame in the warning module doesn't seem to be attached to the outer frame, so you can resize the outer frame left/right and it will grow or shrink appropriately, but resizing up/down does nothing. Normally this would just be a cosmetic issues, but longer previews (e.g. spam-2) cover up the submit button until the window is resized.

Steps to reproduce:
1. Open the warnings module
2. Select {{uw-spam2}}
3. Click `preview`
4. Notice that the submit button is no longer visible
5. Resize the window vertically, notice that the "warning information" frame does not resize with the rest of the frame.

**Comment by siddharthvp** [comment]
Can be fixed by adding `max-height: max-content` to the existing css style for `.ui-dialog.morebits-dialog .morebits-dialog-content`. Not ideal, as it increases the height of the dialog rather providing scrolling, but can be incorporated temporarily until we can come up with something better. @Amorymeltzer

**Comment by Amorymeltzer** [comment]
@siddharthvp Or we just revert #663, which introduced this, and reassess css more carefully.

**Comment by siddharthvp** [comment]
> @siddharthvp Or we just revert #663, which introduced this, and reassess css more carefully.

We could revert the stuff in xfd, coz no one cares much abt the delsort stuff, and because afd nominations can be long and increased size of preview with no in-dialog scrolling will be annoying. But in Warn, I suspect reverting #663 would only drive more folks to turn it off altogether. Also the problem here is less severe since there are just a few long templates and that they are not too long to make the absence of in-dialog scrolling an issue.

**Comment by Amorymeltzer** [comment]
I could've sworn your [proposed change](https://github.com/azatoth/twinkle/issues/665#issuecomment-499905637) was working for me earlier, but it's not now.

This issue will crop up upon resize or for smaller window sizes.

**Comment by siddharthvp** [comment]
Trying refreshing the page a couple of times or clearing the cache. CSS changes aren't easily picked up by browser from my experience in working on this for the last few days.

**Comment by Amorymeltzer** [comment]
@siddharthvp What about undoing the additions from #663 and adding this before the `addCSS`:

```javascript
$('select[name=sub_group]').on('chosen:showing_dropdown', function () {
	$(this).parents('div').css('overflow', 'visible');
});
$('select[name=sub_group]').on('chosen:hiding_dropdown', function () {
	$(this).parents('div').css('overflow', '');
});
```

It's stupid and hacky, but as far as I can tell it takes care of that and this and looks good in Safari, Firefox, and Chrome.

**Comment by siddharthvp** [comment]
Excellent! Though if the preview text is long (made so by using {{uw-spam2}} or another longish template or writing a long optional message) parts of the preview show up below the select menu (when `showing_dropdown`). While this issue can be mitigated by making the select longer, a better solution is to set a small `max-height` and `overflow: hidden` to the previewbox when `showing_dropdown`. wait i'll open a pr.

**Comment by Amorymeltzer** [comment]
See #667 for why my suggestion above doesn't work

**Comment by Amorymeltzer** [comment]
Should have more time tomorrow, but couldn't get it to work.  Tried looking at some more selective/lower css stuff re: #667, but again no luck.

**Comment by Amorymeltzer** [comment]
Oh I see now, I totally misunderstood what you were [saying](https://github.com/azatoth/twinkle/issues/665#issuecomment-499905637) @siddharthvp.  Your suggestion mitigates the issue by changing behavior and extending the dialog, but the underlying problem still exists.  That's where I was getting stuck — my first instinct when the dialog extended down was to resize it, and couldn't for the life of me figure out why tweaking `max-height` was supposed to stop the button from acting weird.

I just put it up on-wiki, since it's probably a net improvement (although who knows anymore...) but yech, this is whole thing is annoying.

----

Perhaps a simpler option, since we don't control the means of chosen CSS production, is to say that extending above and beyond the dialog is less necessary with chosen since the killer app is searching, so just making chosen the height of the dialog could be sufficient.

**Comment by siddharthvp** [comment]
It's easy to understand once you realise the it's _dialog_ acting weird, not the _button_.

What do you say about preventing the dialog from being resizable? `$('.ui-resizable-handle').remove()` ? Now that the dialog can't be resized at all, the bug is fully covered. People would have to use the page's scroll bars if the dialog gets too long. I guess people usually use resize to be able to see all the stuff in the dialog at once. Now that that's going to be case anyway, I don't see much utility in the resize tool.

> Perhaps a simpler option, since we don't control the means of chosen CSS production, is to say that extending above and beyond the dialog is less necessary with chosen since the killer app is searching, so just making chosen the height of the dialog could be sufficient.

That will be fine for xfd's delsort menu, but for Warn, as has been [loudly pointed out](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#User_warning_dialog_dropdown_selector), it wouldn't go down well with users who prefer not to use the search box every time.

**Comment by Amorymeltzer** [comment]
Removing the ability to resize to paper over a stopgap solution is just sweeping it under the rug.

And yes, I'm aware, but the menu has been tightened and lengthened beyond 180px since then, so given that there are only four users opting out, it's possible the opposition would be muted.

**Comment by siddharthvp** [comment]
There are just 4 users opting out because the menu has been lengthened. 

> Removing the ability to resize to paper over a stopgap solution is just sweeping it under the rug.

That may be true, but it doesn't cause any real inconvenience, the way shortening the menu does. The difference is just that you use the page's scroll-bars rather than the dialog's scroll-bars. What's the difference?

**Comment by Amorymeltzer** [comment]
Well, two of them chose it before it had been lengthened, but I don't really want to argue about it.

Regarding the resize handles, I'm not saying `hide()` is a bad stopgap (for a stopgap for a...), but all of this adds up to the warn dialog behaving differently from the rest of Twinkle in a few, apparently quite noticeable, ways.  I still think the `jquery.chosen` menu is a net positive, but it's certainly not a good thing long term.

I'm about to post a comment in #664 that might end up with some tweaks, but after that I say fold this in to a PR.

That being said, isn't `hide`ing the resizers along with the previous plug of `'.ui-dialog.morebits-dialog .morebits-dialog-content { max-height: max-content !important;}'` exactly what would have been needed to similarly paper over the jumping issue from #667?

**Comment by siddharthvp** [comment]
> That being said, isn't hideing the resizers along with the previous plug of '.ui-dialog.morebits-dialog .morebits-dialog-content { max-height: max-content !important;}' exactly what would have been needed to similarly paper over the jumping issue from #667?

**Comment by siddharthvp** [comment]
I only see one noticeable way in which warn dialog has changed - it has search! Ultimately it comes down to whether we wish to make some compromises to accommodate chosen. Unless some CSS god can come over and get #667 to work, or otherwise find an ideal solution without any issues, here are our options:

1. Remove the resizers, in the current setup. The best solution according to me, as already elaborated. 
2. Use a different dialog to show the preview, as done in Welcome module. Now there are no more side-effects for `overflow:visible` to cause. But the  opinions will differ on how good-looking the result is. 
3. Contain chosen within the dialog. I'd prefer # 1 or # 2 over this. 
4. Remove chosen altogether. 

There's another bug in the current setup that's annoying. If someone resizes the textarea horizontally, the textarea along with the fieldset moves out of the dialog. WHile this is obviously coz of `overflow: visible`, I'd ve expected it to be fixed by changing it to `overflow-y: visible`. But that gives totally unexpected results and mangles everything.

> That being said, isn't hideing the resizers along with the previous plug of '.ui-dialog.morebits-dialog .morebits-dialog-content { max-height: max-content !important;}' exactly what would have been needed to similarly paper over the jumping issue from #667?

how do u make that out? did you test this?
