### ISSUE TITLE
Incorrect sorting of protection request as "decrease"

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#666]
https://en.wikipedia.org/wiki/Special:Diff/900846879

**Comment by Amorymeltzer** [comment]
I'll look into this later, but my [initial assessment](https://en.wikipedia.org/w/index.php?title=Wikipedia:Requests_for_page_protection&diff=prev&oldid=900847858&diffmode=source) made it seem like something was misbehaving on-wiki.  Has this happened recently beyond just this instance?

**Comment by ToBeFree** [comment]
Does Twinkle rely on any external replication database for this? Could replag be a thing?

**Comment by Amorymeltzer** [comment]
Helpfully, the only change was #633, which seems an unlikely cause of this.  I got a `pastexpiry` error when I tried to protect via Twinkle's module, which makes me think there was a time/server issue.

**Comment by Amorymeltzer** [comment]
@ToBeFree 	I haven't been able to replicate this, and I haven't seen it since (admittedly, the wiki has been somewhat distracted...), so given that and the weird API error I got when responding to the RfPP request, I'm gonna close this and chock it up to a weird mediawiki hiccough.

*Please do* reopen this if I'm very wrong and it is a recurring issue.
