### ISSUE TITLE
Warn: Combining single-issue notice and warn

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#673]
Given that these are now searchable, the split between single-issue notices and single-issue warnings is not needed as much, and makes it harder to find less-used templates. I suggest that the two tabs be combined, either as a result of the user's preferences or by default. I'd like to work on this, but will hold off for now while waiting for feedback.

**Comment by Amorymeltzer** [comment]
I actually had a request the other day for an "everything" menu — I was thinking of looking into that today or tomorrow — which I think might be an even better way to go.  It raises some interesting questions about what should be the default.

**Comment by Amorymeltzer** [comment]
Well, I threw together a quick *everything* menu, but I think I'm coming around to the idea of a combo singlenotice+singlewarning menu.  The various levels pollute the search result, and make it difficult to navigate: if you want to issue `uw-vandalism3` rather than `uw-vandalism4`, the kitchen sink menu is bad because you need to get in the habit of typing `m3`.  Besides, I've been meaning to try an auto-detect level option, which, if possible, could go nicely with a search-for-singlets menu.

**Comment by Amorymeltzer** [comment]
Regardless, I think this should only be an opt-in choice, as it'd be a pretty radical change.

**Comment by siddharthvp** [comment]
Not really familiar with warning templates, but I think 4im should be kept away from singlenotice+singlewarning.

An _everything_ menu would be good to have separately. That is, in the first dropdown, users can still select "General Note (1)" or "Caution (2)", but they may also select a new "All template warnings" option that would show them all together. And of course, users already have the pref option to set the "default warning level", which they may set to "All template warnings" if they want. This way, there's no need to make the feature opt-in.

**Comment by Amorymeltzer** [comment]
I meant "opt-in" to cover the gamut from "replace the two with one" to "add one," it would of course be molded as a user pref option.
